### ISSUE TITLE
Bot: Caesar cypher

### ISSUE THREAD

**Issue by charleso** [charleso/haskell-in-haste#9]

**Comment by NaevaTheCat** [comment]
Implemented a basic one. Let me know what you think of it/how difficult. I think map should be moved from the bot so the students can play with it. There is also the potential for a lot of pain/pitfalls if they don't treat [A..Z] as a circular list. Plenty of room for finding simple solutions for handling upper/lower case punctation etc _if_ they know what id is. Otherwise harder.

My way involves lookup, it could also be done by mapping some numerical conversion over the characters. That would be painful for them to type but providing it would probably make them feel like they should use it?

let me know your thoughts.

**Comment by charleso** [comment]
For reference:

https://github.com/charleso/haskell-in-haste/pull/14
